name: Secret Scanning Review

on:
  pull_request:

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
      contents: read

    steps:
      - uses: advanced-security/secret-scanning-review-action@v1
        with:
          fail-on-alert: true